# -*- coding: utf-8 -*-
"""ProjetoLogicadeprogramação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmmRv_PziUdUe8yPyUGx4BR0_Lr7gCgX
"""



import os

def limpar_tela():
    """Limpa o console de acordo com o sistema operacional."""
    os.system('cls' if os.name == 'nt' else 'clear')

def exibir_tabuleiro(tabuleiro):
    """Imprime o tabuleiro na tela.ok"""
    print("\n")
    print(f" {tabuleiro[0]} | {tabuleiro[1]} | {tabuleiro[2]} ")
    print("---|---|---")
    print(f" {tabuleiro[3]} | {tabuleiro[4]} | {tabuleiro[5]} ")
    print("---|---|---")
    print(f" {tabuleiro[6]} | {tabuleiro[7]} | {tabuleiro[8]} ")
    print("\n")

def verificar_vitoria(tabuleiro, jogador):
    """Verifica se o jogador atual venceu."""
    # Condições de vitória: linhas, colunas e diagonais
    condicoes = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8],  # Linhas
        [0, 3, 6], [1, 4, 7], [2, 5, 8],  # Colunas
        [0, 4, 8], [2, 4, 6]              # Diagonais
    ]
    for condicao in condicoes:
        if tabuleiro[condicao[0]] == tabuleiro[condicao[1]] == tabuleiro[condicao[2]] == jogador:
            return True
    return False

def jogo_da_velha():
    # Inicializa o tabuleiro com números de 1 a 9 para guiar o jogador
    tabuleiro = [str(i) for i in range(1, 10)]
    jogador_atual = "X"
    jogadas = 0

    print("--- BEM-VINDO AO JOGO DA VELHA ---")

    while jogadas < 9:
        exibir_tabuleiro(tabuleiro)

        try:
            escolha = int(input(f"Jogador [{jogador_atual}], escolha uma posição (1-9): ")) - 1
        except ValueError:
            print("Por favor, digite um número válido!")
            continue

        # Valida a jogada
        if escolha < 0 or escolha > 8 or tabuleiro[escolha] in ["X", "O"]:
            print("Posição inválida ou já ocupada! Tente novamente.")
            continue

        # Marca a jogada e atualiza o contador
        tabuleiro[escolha] = jogador_atual
        jogadas += 1

        # Verifica vitória
        if verificar_vitoria(tabuleiro, jogador_atual):
            exibir_tabuleiro(tabuleiro)
            print(f"Parabéns! O jogador [{jogador_atual}] venceu!")
            return

        # Alterna o jogador
        jogador_atual = "O" if jogador_atual == "X" else "X"

    # Se sair do loop sem vitória, deu empate
    exibir_tabuleiro(tabuleiro)
    print("O jogo empatou! (Deu velha 👵)")

# Executa o jogo
if __name__ == "__main__":
    jogo_da_velha()

import os

def limpar_tela():
    """Limpa o terminal para manter o visual organizado."""
    os.system('cls' if os.name == 'nt' else 'clear')

def exibir_tabuleiro(tabuleiro):
    """Desenha o tabuleiro na tela com espaçamento limpo."""
    print("\n      JOGO DA VELHA")
    print("     =============== \n")
    print(f"        {tabuleiro[0]} | {tabuleiro[1]} | {tabuleiro[2]} ")
    print("       ---+---+---")
    print(f"        {tabuleiro[3]} | {tabuleiro[4]} | {tabuleiro[5]} ")
    print("       ---+---+---")
    print(f"        {tabuleiro[6]} | {tabuleiro[7]} | {tabuleiro[8]} \n")
    print("     =============== \n")

def verificar_vitoria(tab, jog):
    """Checa todas as combinações lineares para encontrar um vencedor."""
    vitorias = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # Linhas
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # Colunas
        [0, 4, 8], [2, 4, 6]             # Diagonais
    ]
    return any(all(tab[pos] == jog for pos in linha) for linha in vitorias)

def jogar():
    """Gerencia o fluxo principal do jogo."""
    # Preenche o tabuleiro inicial com os números das posições (1 a 9)
    tabuleiro = [str(i) for i in range(1, 10)]
    jogador_atual = "X"
    jogadas = 0

    while jogadas < 9:
        limpar_tela()
        exibir_tabuleiro(tabuleiro)

        try:
            escolha = int(input(f"Jogador '{jogador_atual}', escolha uma posição (1-9): ")) - 1

            if escolha < 0 or escolha > 8 or tabuleiro[escolha] in ["X", "O"]:
                print("\n⚠️ Posição inválida ou já ocupada! Tente novamente.")
                input("Pressione Enter para continuar...")
                continue

        except ValueError:
            print("\n⚠️ Por favor, digite apenas números entre 1 e 9!")
            input("Pressione Enter para continuar...")
            continue

        # Marca a jogada no tabuleiro
        tabuleiro[escolha] = jogador_atual
        jogadas += 1

        # Verifica se o jogador atual venceu
        if verificar_vitoria(tabuleiro, jogador_atual):
            limpar_tela()
            exibir_tabuleiro(tabuleiro)
            print(f"🎉 PARABÉNS! O jogador '{jogador_atual}' venceu o jogo! 🎉\n")
            return

        # Alterna o turno entre X e O
        jogador_atual = "O" if jogador_atual == "X" else "X"

    # Se o loop terminar sem retornos, é porque deu velha
    limpar_tela()
    exibir_tabuleiro(tabuleiro)
    print("🤝 Deu Velha! O jogo terminou em empate.\n")

if __name__ == "__main__":
    jogar()

import os

def limpar_tela():
    """Limpa o terminal para manter o visual organizado."""
    os.system('cls' if os.name == 'nt' else 'clear')

def exibir_tabuleiro(tabuleiro):
    """Desenha o tabuleiro na tela com espaçamento limpo."""
    print("\n      JOGO DA VELHA")
    print("     =============== \n")
    print(f"        {tabuleiro[0]} | {tabuleiro[1]} | {tabuleiro[2]} ")
    print("       ---+---+---")
    print(f"        {tabuleiro[3]} | {tabuleiro[4]} | {tabuleiro[5]} ")
    print("       ---+---+---")
    print(f"        {tabuleiro[6]} | {tabuleiro[7]} | {tabuleiro[8]} \n")
    print("     =============== \n")

def verificar_vitoria(tab, jog):
    """Checa todas as combinações lineares para encontrar um vencedor."""
    vitorias = [
        [0, 1, 2], [3, 4, 5], [6, 7, 8], # Linhas
        [0, 3, 6], [1, 4, 7], [2, 5, 8], # Colunas
        [0, 4, 8], [2, 4, 6]             # Diagonais
    ]
    return any(all(tab[pos] == jog for pos in linha) for linha in vitorias)

def jogar():
    """Gerencia o fluxo principal do jogo."""
    # Preenche o tabuleiro inicial com os números das posições (1 a 9)
    tabuleiro = [str(i) for i in range(1, 10)]
    jogador_atual = "X"
    jogadas = 0

    while jogadas < 9:
        limpar_tela()
        exibir_tabuleiro(tabuleiro)

        try:
            escolha = int(input(f"Jogador '{jogador_atual}', escolha uma posição (1-9): ")) - 1

            if escolha < 0 or escolha > 8 or tabuleiro[escolha] in ["X", "O"]:
                print("\n⚠️ Posição inválida ou já ocupada! Tente novamente.")
                input("Pressione Enter para continuar...")
                continue

        except ValueError:
            print("\n⚠️ Por favor, digite apenas números entre 1 e 9!")
            input("Pressione Enter para continuar...")
            continue

        # Marca a jogada no tabuleiro
        tabuleiro[escolha] = jogador_atual
        jogadas += 1

        # Verifica se o jogador atual venceu
        if verificar_vitoria(tabuleiro, jogador_atual):
            limpar_tela()
            exibir_tabuleiro(tabuleiro)
            print(f"🎉 PARABÉNS! O jogador '{jogador_atual}' venceu o jogo! 🎉\n")
            return

        # Alterna o turno entre X e O
        jogador_atual = "O" if jogador_atual == "X" else "X"

    # Se o loop terminar sem retornos, é porque deu velha
    limpar_tela()
    exibir_tabuleiro(tabuleiro)
    print("🤝 Deu Velha! O jogo terminou em empate.\n")

if __name__ == "__main__":
    jogar()